// <auto-generated />
namespace G3_Practice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class CorreccionAPedidos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CorreccionAPedidos));
        
        string IMigrationMetadata.Id
        {
            get { return "202411161800122_CorreccionAPedidos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
