// <auto-generated />
namespace G3_Practice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AgregarDireccionEntregaMetodoPagoAPedido : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AgregarDireccionEntregaMetodoPagoAPedido));
        
        string IMigrationMetadata.Id
        {
            get { return "202411152012504_AgregarDireccionEntregaMetodoPagoAPedido"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
