// <auto-generated />
namespace G3_Practice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Ojala_Funcione : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ojala_Funcione));
        
        string IMigrationMetadata.Id
        {
            get { return "202411141519583_Ojala_Funcione"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
